classDiagram
  class Animal {
    <<abstract>>
  }
  class Dog
  class A
  class B
  class C
  class PetOwner {
    <<mixin>>
  }
  class DogRepository
  class Runnable {
    <<interface>>
  }
  class Shape {
    <<sealed>>
  }
  class Circle
  class Rect
  class Status {
    <<enumeration>>
  }
  class Swimmer {
    <<mixin>>
  }

  A <|-- B : extends
  Animal <|-- Dog : extends
  Animal <|.. Swimmer : with
  B <|-- C : extends
  Comparable <|.. Status : implements
  DogRepository --> Animal : uses
  DogRepository --> Dog : uses
  PetOwner <|.. Dog : with
  Runnable <|.. Dog : implements
  Shape <|-- Circle : extends
  Shape <|-- Rect : extends
  Swimmer <|.. Dog : with
