import '../models/class_info.dart';
import 'mermaid_generator.dart';

/// Generates HTML visualization of Mermaid diagrams.
class HtmlGenerator {
  /// Generate HTML with embedded Mermaid diagram.
  String generateHtml(List<ClassInfo> classes, {bool noPrivate = false, bool noExternal = false, bool noMethods = false, Set<String>? onlyRelations}) {
    final mermaidGenerator = MermaidGenerator();
    final diagramCode = mermaidGenerator.generate(classes, noPrivate: noPrivate, noExternal: noExternal, noMethods: noMethods, onlyRelations: onlyRelations);

    return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dart Class Diagram</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }

        .container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            padding: 40px;
            max-width: 1200px;
            width: 100%;
        }

        h1 {
            color: #333;
            margin-bottom: 10px;
            font-size: 28px;
        }

        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 14px;
        }

        .diagram-wrapper {
            display: flex;
            justify-content: center;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
            border: 1px solid #e0e0e0;
            overflow-x: auto;
        }

        .mermaid {
            display: flex;
            justify-content: center;
        }

        .info {
            margin-top: 30px;
            padding: 20px;
            background: #f0f7ff;
            border-left: 4px solid #667eea;
            border-radius: 4px;
            color: #333;
        }

        .info h3 {
            margin-bottom: 10px;
            color: #667eea;
        }

        .info p {
            margin: 8px 0;
            line-height: 1.6;
            font-size: 14px;
        }

        .info code {
            background: white;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            color: #d63384;
        }

        footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Dart Class Diagram</h1>
        <div class="subtitle">Generated by diagram_dart</div>

        <div class="diagram-wrapper">
            <div class="mermaid">
$diagramCode
            </div>
        </div>

        <div class="info">
            <h3>Diagram Legend</h3>
            <p>
                <strong>Arrows:</strong><br>
                • Solid arrow <code>&lt;|--</code> = extends (inheritance)<br>
                • Dashed arrow <code>&lt;|..</code> = implements (interface)<br>
                • Dashed arrow <code>&lt;|..</code> = with (mixin)<br>
                • Composition arrow <code>--&gt;</code> = uses (field type)
            </p>
            <p>
                <strong>Annotations:</strong><br>
                • <code>&lt;&lt;abstract&gt;&gt;</code> = Abstract class<br>
                • <code>&lt;&lt;interface&gt;&gt;</code> = Interface class<br>
                • <code>&lt;&lt;sealed&gt;&gt;</code> = Sealed class<br>
                • <code>&lt;&lt;mixin&gt;&gt;</code> = Mixin<br>
                • <code>&lt;&lt;enumeration&gt;&gt;</code> = Enum
            </p>
        </div>
    </div>

    <footer>
        <p>Generated by diagram_dart • Mermaid diagram rendering</p>
    </footer>

    <script>
        mermaid.initialize({ startOnLoad: true, theme: 'default', maxTextSize: 500000 });
        mermaid.contentLoaded();
    </script>
</body>
</html>''';
  }
}
